### ISSUE TITLE
v1.0.0-d25c1fd:beta - Snapshot height issue

### ISSUE THREAD

**Issue by alexdelprete** [jakowenko/double-take#101]
I'm trying to implement face recognition for my doorbell with Double Take. My doorbell has a 1536*2048 resolution, it's working fine with Frigate since 2 years.

Now, I needed to pass a full height snapshot to Double Take because of the face box size that was under minimum requirements with a height of 512. So I configured Double Take with this:

```
  attempts:
    # number of times double take will request a frigate latest.jpg for facial recognition
    latest: 0
    # number of times double take will request a frigate snapshot.jpg for facial recognition
    snapshot: 5
    # process frigate images from frigate/+/person/snapshot topics
    mqtt: true
    # add a delay expressed in seconds between each detection loop
    delay: 0

    image:
      # height of frigate image passed for facial recognition
      height: 2048
```

And Frigate like this:

```
    # Optional: Configuration for the jpg snapshots published via API
    snapshots:
      enabled: True
      clean_copy: False
      timestamp: False
      bounding_box: True
      crop: False
      height: 2048
      retain:
        default: 5 

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: shown below)
      height: 2048
      # Optional: jpeg encode quality (default: shown below)
      quality: 80
```

The problem is that the MQTT snapshot is correct, with a height of 2048, the snapshot is **always** an image with a 500 height no matter what value I use for image height in Double Take's config. I also checked under Frigate's clips folder, and found out that the images wrote there are indeed 2048 in height. Are those the actual ones passed via API to apps like Double Take?

I also had to disable latest.jpg API access because that image has not a fixed size, it's dynamic and I found no way to configure it in Frigate.

Thanks.

**Comment by alexdelprete** [comment]
When Double Take calls frigate's API for the snapshot, does it request a specific height, the one configured under the image: setting?

https://blakeblackshear.github.io/frigate/usage/api/#apieventsidsnapshotjpg

![image](https://user-images.githubusercontent.com/7027842/134002365-df9a0bc4-3c62-4016-b2c2-bd95dea895a5.png)

**Comment by jakowenko** [comment]
Hey @alexdelprete, when Frigate's API is used it does request a specific height. [Here](https://github.com/jakowenko/double-take/blob/beta/api/src/controllers/recognize.controller.js#L117) is the part of the code where that happens.

The snapshot.jpg and latest.jpg sizes are controlled from Double Take, but I think I have the indentation wrong in the beta docs currently.

Try nesting it like this.

```yaml
frigate:
  url: http://frigate:5000
  image:
    height: 2048
```
