### ISSUE TITLE
Deepstack: Face endpoints not activated

### ISSUE THREAD

**Issue by Calimerorulez** [jakowenko/double-take#103]
Hi,

Thank you for your great work.
I'm trying to connect to Deepstack, but Double-take says 'Face endpoints not activated', on the hover of the red dot for Deepstack.

What am I missing?
Thanks!

**Comment by jakowenko** [comment]
Hey! Do you have `VISION-FACE` set as an `environment` variable for your DeepStack container?

```yaml
version: '3.7'

services:
  deepstack:
    container_name: deepstack
    image: deepquestai/deepstack
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      VISION-FACE: 'True'
```
