### ISSUE TITLE
docker-versioning ?

### ISSUE THREAD

**Issue by ozett** [jakowenko/double-take#108]
maybe helpful to get versions on the docker-images like frigate does?
i now want to pull 1.0, but hard to see the versioning here https://github.com/jakowenko/double-take#docker-compose

maybe there is a dockercompose convention to get specific versions? 

??   image: jakowenko/double-take:1.0.0 ?

thats what i have:
```
services:
  double-take:
    container_name: double-take
    image: jakowenko/double-take
    #image: jakowenko/double-take:0.10.2
    #image: jakowenko/double-take:beta-1.0.0
    #image: jakowenko/double-take:beta
```

```
    #image: blakeblackshear/frigate:stable-amd64
    #beta
    #image: blakeblackshear/frigate:0.9.0-beta2-amd64
    #image: blakeblackshear/frigate:0.9.0-rc1-amd64
    # rc
    #image: blakeblackshear/frigate:0.9.0-rc2-amd64
    #image: blakeblackshear/frigate:0.9.0-rc3-amd64
    image: blakeblackshear/frigate:0.9.0-rc4-amd64
```
