### ISSUE TITLE
[FR] Ability to override Frigate `latest.jpg` and `snapshot.jpg`

### ISSUE THREAD

**Issue by jakowenko** [jakowenko/double-take#110]
Continuing the discussion from #102 @hawkeye217 is looking for a way to override the `latest.jpg` and `snapshot.jpg` images rather than using the default ones from Frigate's API.

Here is my proposed solution.

```yaml
frigate:
  url: https://frigate.com:5000
  
  # defaults applied to all cameras and events
  attempts:
    # number of times double take will request a frigate latest.jpg for facial recognition
    latest: 10
    # number of times double take will request a frigate snapshot.jpg for facial recognition
    snapshot: 0
    # process frigate images from frigate/+/person/snapshot topics
    mqtt: true
    # add a delay expressed in seconds between each detection loop
    delay: 0

  image:
    # height of frigate image passed for facial recognition
    height: 500

  # override global frigate attempts and images per camera
  events:
    office:
      attempts:
        latest: 0
        snapshot: 5
        mqtt: false
        delay: 0

      image:
        height: 600
        snapshot: http://snapshot-url.com/image.jpg
        latest: http://latest-url.com/image.jpg
```

With this configuration the `office` camera has new values applied to it. I've disabled the `latest` processing by setting the `attempts.latest` to `0`. The MQTT snapshot is also disabled by setting `attempts.mqtt` to `false`. You can also override the `snapshot.jpg` or `latest.jpg` image instead of using the ones provided from Frigate's API.

You can also change the `image.height` per camera, but this will only apply to the standard `latest.jpg` and `snapshot.jpg` images from Frigate. In the above example because I have a custom value for `latest` and `snapshot`, then the height will be omitted.

-----

@hawkeye217 I have all of these changes above ready locally. Just want to make sure the above makes sense before I release a new beta build with this. Let me know what you think!

**Comment by hawkeye217** [comment]
Looks like it will do what I need and more! Thanks!

**Comment by jakowenko** [comment]
> Looks like it will do what I need and more! Thanks!

Awesome, thanks for the quick reply! I'll get this pushed up tonight and let you know when it's ready to test 🤞

**Comment by Sylvain-Laine** [comment]
It's awesome, it fits my needs to !

**Comment by jakowenko** [comment]
Hey @hawkeye217 and @Sylvain-Laine, this is ready for testing! The latest beta should include it `docker pull jakowenko/double-take:beta`.

Hopefully I didn't break anything haha! Let me know if it works and what you think.

I updated the [README](https://github.com/jakowenko/double-take/tree/beta#frigate-1) to include the new options.

**Comment by Sylvain-Laine** [comment]
So far it works !
Im going to let it run this morning and test a bit more !
Thanks

**Comment by hawkeye217** [comment]
Thanks for the fast turnaround! I'll install it and test it today.

**Comment by hawkeye217** [comment]
Tested the beta on my doorbell cam and another interior cam. It all seems to be working great for the doorbell cam, but the interior cam's snapshot url requires a username and password as follows:

`http://username:password@192.168.1.10/snapshot.cgi`

I'm guessing the way you've set up axios doesn't allow for that, as I'm getting a 401 (unauthorized) error:

```
error: Error: url validation error: Request failed with status code 401
    at createError (/double-take/api/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/double-take/api/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/double-take/api/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by jakowenko** [comment]
Hm...glad it's working at least for one of them. I haven't tried any URLs before that have username:password in them.

Does going to `http://username:password@192.168.1.10/snapshot.cgi` directly in your browser render the image OK?

**Comment by hawkeye217** [comment]
Yes it does. The browser does basic authentication based on the username and password in the url.

Axios requires a `header` object to do basic auth. There probably is an easy way to take the keys from the url, but I'm just not familiar with it.

**Comment by jakowenko** [comment]
Ah, I didn't know the browser did that in the background. Ya it should be pretty easier to take that out of the URL then split it based on the `:` value to get `username` and `password`. I'll try to sneak this fix in tonight.

```javascript
await axios.get(url, {}, {
  auth: {
    username,
    password
  }
});
```

**Comment by jakowenko** [comment]
I tried to test this with `http://foo:bar@httpbin.org/basic-auth/foo/bar` as the URL. It works when I set my image to be the URL with the auth in it.

Did you try that as well?

The below worked and at least passed that URL check. When I remove `foo:bar` I get the `401` like you had.

```yaml
  events:
    office:
      image:
        latest: http://foo:bar@httpbin.org/basic-auth/foo/bar
```
