### ISSUE TITLE
pulling latest docker automically?

### ISSUE THREAD

**Issue by ozett** [jakowenko/double-take#116]
restarting my docker-compose with double-take:latest is not automatically pulling ver1.2.
still my old ver1.0.  is there no automatic pull for latest? or is my tagging wrong?

```
# double-take
version: '3.7'

services:
  double-take:
    container_name: double-take
    #image: jakowenko/double-take
    #image: jakowenko/double-take:0.10.2
    #image: jakowenko/double-take:beta-1.0.0
    #image: jakowenko/double-take:1.2.0
    image: jakowenko/double-take:latest
    #image: jakowenko/double-take:beta

    restart: unless-stopped
    volumes:
      #- ${PWD}/.storage:/.storage
      - /usr/src/media:/.storage
      # config?
      #- /usr/src/doubltake.yml:/config/config.yml:ro
    ports:
      - 3000:3000
     ```
