### ISSUE TITLE
[FEAT] Subscribe to events from eufy-mqtt-bridge

### ISSUE THREAD

**Issue by jonwilliams84** [jakowenko/double-take#119]
Is there a way to subscribe to events from eufy mqtt bridge for "Person Detected" events and process the thumbnail?

Looking at the code in https://github.com/matijse/eufy-ha-mqtt-bridge person detected events are published to these topics

```     
 case NotificationType.EVENT_PERSON_DETECTED:
        return `homeassistant/binary_sensor/eufy/${deviceSN}_person`

 case NotificationType.THUMBNAIL:
       return `homeassistant/camera/eufy/${deviceSN}_thumbnail`
```

Essentially I would like double-take to listen for such events and process the thumbnail.

**Comment by jakowenko** [comment]
Hey, thanks for the suggestion and the info about that Eufy project. I run a few Eufy cameras and had no idea that bridge existed, that's pretty cool!

There is a way to support this currently and I also just pushed a new beta build to make sure to pull in the right camera name based off the config. Here's how you'll need to setup your config to pull in those images. One thing to note is the quality / size of these thumbnails may not produce the best results, but I was able to verify it worked with the two Eufy's I have here.

```yaml
cameras:
  back-door:
    snapshot:
      topic: homeassistant/camera/eufy/${deviceSN}_thumbnail
  family-room:
    snapshot:
      topic: homeassistant/camera/eufy/${deviceSN}_thumbnail
```

And the result looks like this (disregard all the amazon boxes haha)
<img width="273" alt="Screen Shot 2021-10-07 at 1 30 39 AM" src="https://user-images.githubusercontent.com/1081811/136325684-244dd84e-1d55-472f-9b59-226e28332829.png">
