### ISSUE TITLE
[FEAT] Snapshot url digest auth

### ISSUE THREAD

**Issue by miguelangel-nubla** [jakowenko/double-take#128]
As discussed in [#110](https://github.com/jakowenko/double-take/issues/110#issuecomment-939396423) custom snapshot url's do not work with digest auth servers.

It should be useful with many cameras.

**Comment by jakowenko** [comment]
I have a working version locally to support this. I wanted to see what you think of this setup.

Because you can use these http images in various places in the config, I wanted to put the auth for them in a single spot.

During the API calls the code will check to see if there's a matching `digest-auth` object based off the `url`.

Let me know if this makes sense and will work for you. I can push up a beta build for this tonight if you'd like to test it.

```yaml
digest-auth:
  - url: https://httpbin.org/digest-auth/auth/user/pass
    username: user
    password: pass
  - url: http://camera-url-1.com/latest.jpg
    username: admin
    password: admin

cameras:
  test:
    snapshot:
      url: https://httpbin.org/digest-auth/auth/user/pass

frigate:
  url: https://frigate.jako.io
  events:
    office:
      image:
        latest: https://httpbin.org/digest-auth/auth/user/pass
```
