### ISSUE TITLE
[BUG] Home assistant automation does not fire

### ISSUE THREAD

**Issue by balonchiks** [jakowenko/double-take#140]
**Describe the bug**
Hi, I have setup MQTT integration and the sensors have successfully been created and are visible in home assistant (both for _sensor.double_take_myname_ and _sensor.double_take_unknown_), however the automation that i took from config example does not seem to fire for me.

It looks like when the face matches, only the attributes of _sensor.double_take_myname_ are changed while the state of the sensor remains unchanged, hence the automation does not pick it up as a state change and hence the automation does not fire in home assistant. I am using only 1 camera named entrance and the state of my _sensor.double_take_myname_ is always entrance and is never changed.

Here is the automation i am using in home assistant:

```
- alias: Double take
  trigger:
    - platform: state
      entity_id: sensor.double_take_myname
  condition:
    - condition: template
      value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
  action:
    - service: notify.me
      data:
        message: "{% if trigger.to_state.attributes.match is defined %}
                    {{trigger.to_state.attributes.friendly_name}} is at the {{trigger.to_state.state}} matched with {{trigger.to_state.attributes.match.confidence}}% confidence taking {{trigger.to_state.attributes.attempts}} attempt(s) @ {{trigger.to_state.attributes.duration}} sec
                  {% elif trigger.to_state.attributes.unknown is defined %}
                    unknown is at the {{trigger.to_state.state}} matched with {{trigger.to_state.attributes.unknown.confidence}}% confidence taking {{trigger.to_state.attributes.attempts}} attempt(s) @ {{trigger.to_state.attributes.duration}} sec
                  {% endif %}"
  mode: parallel
  max: 3
```

Is there something i am doing wrong, or is it a bug?

**Version of Double Take**
1.5.2

**Expected behavior**
Expect automation to fire each time a detection happens
