### ISSUE TITLE
Entities containing trained faces not showing up in Home Assistant

### ISSUE THREAD

**Issue by Iceman248** [jakowenko/double-take#148]
I'm new to this, have gotten the name of camera and unknown entities to show up through MQTT, but a trained person will not. Am I missing something?

**Comment by jakowenko** [comment]
Do images show up on the *matches* page on the UI? If the box around the detector name is red it means it wasn't considered a match. Clicking on the red text shows why, as you can see in the screenshot below.

You can adjust the `min_area` and `confidence` values to your needs to increase the changes of a match depending on the detection result. Once an image is considered a match, then it will be published to MQTT and should be picked up in Home assistant as `sensor.double_take_<name>`.

![Screen Shot 2021-10-29 at 8 22 59 PM](https://user-images.githubusercontent.com/1081811/139513593-b1769d42-04e9-4db8-9281-788705b98cb6.png)

**Comment by Iceman248** [comment]
Box area too low is stopping it even though some have a name. None of them are close to the 10000 number. Highest around 4000, but many much lower. I set up the camera I'm testing it on to use snapshot image using snapshot URL from my Dahua IP Cam 2MP (1920x1080). Frigate detection running at 1280x720, some of those "latest" or "snapshot" from Frigate are part of the results as well as that snapshot URL I programmed into this app.

With that 1080 resolution, how would I box score be so incredibly low?

**Comment by jakowenko** [comment]
The name vs unknown is controlled by another setting. If the `confidence` is above the `unknown.confidence` value then the name is kept, if it's below it goes to `unknown`. For the `sensor.double_take_<name>` topic to be updated the result needs to be considered a match.

I would adjust the `min_area` based on how far faces are from the camera typically. You can even adjust it per camera if you want. The default is set to `10000` which just means the box around the face needs to be at least 100x100 pixels. I've changed mine to `min_area: 2500` which would be 50x50 pixels.

```yaml
detect:
  match:
    # minimum confidence needed to consider a result a match
    confidence: 60
    # minimum area in pixels to consider a result a match
    min_area: 10000

  unknown:
    # minimum confidence needed before classifying a name as unknown
    confidence: 40
    # minimum area in pixels to keep an unknown result
    min_area: 0
```
