### ISSUE TITLE
[FEAT] min_area per detector

### ISSUE THREAD

**Issue by balonchiks** [jakowenko/double-take#153]
**Is your feature request related to a problem? Please describe.**

Would be great to the possibility to set see `min_area`: per detector, as the bounding box with compreface and deepstack usually differs in size for me, with the deepstack having a noticeably smaller bounding box and hence would be great to set the `min_area` lower for that detector.

Example:

```
detectors:
  compreface:
    url: http://10.0.0.0:7000
    key: xxxxxxxxx
    min_area: 10000
  deepstack:
    url: http://10.0.0.0:5555
    min_area: 5000
```
