### ISSUE TITLE
[BUG] Connect to external MQTT with fixed client_id

### ISSUE THREAD

**Issue by erigmac** [jakowenko/double-take#168]
**Describe the bug**
Can’t connect to external MQTT broker due to not being able to specify fixed client_id.
I am using VerneMQ with PostgreSQL database authentication

**Version of Double Take**
```v1.6.0-893328f```

**Expected behavior**
DoubleTake should allow for specifying client_id or otherwise provide the client_id to be able to authenticate to database authenticated MQTT broker

**Hardware**
- OS: Home Assistant Operating System
- Browser: Safari

**Additional context**
```yaml
# Double Take
mqtt:
  host: 10.0.0.13
  client_id: <CLIENT_ID>
  user: <USER>
  password: <PASS>

frigate:
  url: http://10.0.0.14:5000

detectors:
  deepstack:
    url: http://10.0.0.15
```

**Comment by jakowenko** [comment]
Hey @erigmac, just pushed a new beta build to include this feature. Let me know if it works for you!

```yaml
mqtt:
  host: 10.0.0.13
  client_id: <CLIENT_ID>
```
