### ISSUE TITLE
[FEAT] Storing Secrets

### ISSUE THREAD

**Issue by TonyBrobston** [jakowenko/double-take#170]
My apologies if this is covered somewhere and I missed it. Is there a pattern for dealing with secrets, passwords, things you don't want directly in your config?

I see that Frigate uses a pattern where you can create environment variables prefixed with `FRIGATE_` and then reference them in yaml by wrapping the environment variable in curly braces `{FRIGATE_MQTT_PASSWORD}`, does something like this exist in Double Take?

If Double Take does not have this yet, it seems like using the same pattern as Frigate could make this straight forward for users?

My main issue is that my mqtt-broker has a username/password and I would like to keep my mqtt password out of my config file; often times I leave these config files open source and reference them.

Thanks for the work on this repo, it is a much needed tool and I look forward to working with it more!

**Comment by jakowenko** [comment]
Hey @TonyBrobston, thanks for the great suggestion. I pushed a new beta build to include this ability. I modeled it similar to how Home Assistant does it.

Let me know what you think!

Create a `secrets.yml` file in the `/config` directory to store private information outside of `config.yml`. Use `!secret` and an identifier.

```yaml
mqtt:
  host: localhost
  username: mqtt
  password: !secret mqtt_password

detectors:
  compreface:
    url: localhost:8000
    key: !secret compreface_key
```

The `secrets.yaml` file contains the corresponding value assigned to the identifier.

```yaml
mqtt_password: <password>
compreface_key: <api-key>
```
