### ISSUE TITLE
[BUG] - No files found rotating indefinitely 

### ISSUE THREAD

**Issue by patrik-malina** [jakowenko/double-take#174]
**Describe the bug**
Double take connect to frigate, mqtt and facebox (green lights), but must to use IP to connect. Cannot use localhost. I have HA installed on Proxmox as VM.
Frigate capturing objects.
Facebox working fine on itself (IP:8001).
CompreFace not worked/nor DeppStack because they wish to connect to localhost:port....

Maches page shows no file found and rotate indefinitely... but logs shows its processing images. Sometimes shows Red notice Network error.

**Version of Double Take**
1.7.0.-bf3e911

**Hardware**
 - OS: Home Assistant OS 6.6
 - Browser Edge (windows 11)

**Additional context**
Config file:
```
mqtt:
  host: 192.168.0.104
  username: xxxx
  password: xxxx

  topics:
    frigate: frigate/events
    homeassistant: homeassistant
    matches: double-take/matches
    cameras: double-take/cameras

frigate:
  url: http://192.168.0.104:5000

  labels:
    - person
    
detectors:
    facebox:
      url: http://192.168.0.104:8001
      timeout: 15

```
