### ISSUE TITLE
CompreFace API Error 404 not found 

### ISSUE THREAD

**Issue by mattexpa** [jakowenko/double-take#190]
Hello,

i've set up double take to use deepstack and compreface as detectors as configured as following:
```
detectors:
  deepstack:
    url: http://deepstack:5000
    key: 
    # number of seconds before the request times out and is aborted
    timeout: 15

  compreface:
    url: http://compreface:3000
    # recognition api key
    key: bc3475e3-0961-4d44-bf2a-0992cacb6de4
    # number of seconds before the request times out and is aborted
    timeout: 15
    # minimum required confidence that a recognized face is actually a face
    # value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # comma-separated slugs of face plugins
    # https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md)
    # face_plugins: mask,gender,age
```

Complete Environment is running on Docker controlled via Unraid.
Compreface Container running fine - no errors whatsoever but when connecting DT to CompreFace API the following error appears in the CF Container logs:

`{"severity": "WARNING", "message": "404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", "request": {"method": "POST", "path": "/api/v1/recognition/recognize?face_plugins=undefined&det_prob_threshold=0", "filename": "", "api_key": "bc3475e3-0961-4d44-bf2a-0992cacb6de4", "remote_addr": "192.168.2.101"}, "logger": "root", "module": "error_handling", "traceback": "Traceback (most recent call last):\n File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n rv = self.dispatch_request()\n File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1926, in dispatch_request\n self.raise_routing_exception(req)\n File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1908, in raise_routing_exception\n raise request.routing_exception\n File \"/usr/local/lib/python3.7/site-packages/flask/ctx.py\", line 350, in match_request\n result = self.url_adapter.match(return_rule=True)\n File \"/usr/local/lib/python3.7/site-packages/werkzeug/routing.py\", line 1945, in match\n raise NotFound()\nwerkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.\n", "build_version": "dev"}
`
And on the DT GUI the following tooltip gets thrown: 
```
{
	"message": "404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."
}
```

I tried everything but can't get my head wrapped around this - some help would be greatly appreciated!

**Comment by mattexpa** [comment]
For some strange Reason i fixed this by simply removing the port after the url of CF.
Working config example:
```
compreface:
    url: http://compreface
    # recognition api key
    key: bc3475e3-0961-4d44-bf2a-0992cacb6de4
    # number of seconds before the request times out and is aborted
    timeout: 15
    # minimum required confidence that a recognized face is actually a face
    # value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # comma-separated slugs of face plugins
    # https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md)
    # face_plugins: mask,gender,age
```
