### ISSUE TITLE
Exclude cameras

### ISSUE THREAD

**Issue by leoveejay** [jakowenko/double-take#222]
Congratulations on the job!
I have Frigate installed with 5 cameras but I would like double-take to only work on three of them would this be possible?

Thanks
Leo

**Comment by jakowenko** [comment]
Hello and thank you!

Yes, you can configure Frigate to only process images from certain cameras. Here's the [full config example](https://github.com/jakowenko/double-take#frigate-1), but a simple one would look something like this.

```yaml
frigate:
  url: http://my-frigate-url.com
  # only process images from specific cameras
  cameras:
    - camera-name
    - garage
    - front-door
 ```
