### ISSUE TITLE
[FEAT] Retrieve image without using the API

### ISSUE THREAD

**Issue by totalitarian** [jakowenko/double-take#231]
Hi,

I'm trying to send images to my mobile using the automation mentioned here 

https://github.com/jakowenko/double-take#home-assistant

While this works locally, I have to open up port 3000 on my router to make it work remotely.

I'd like to not have to punch another hole in my router if possible. Is there anyway to access this file another way? Maybe by copying it into the www folder somehow?

**Comment by LordNex** [comment]
I believe if your running DT inside Home assistant that you can use it's default port of 8123. Which you probably have open anyway for HA access if you use it.

**Comment by robchandhok** [comment]
There should be an ingress path, but it appears to me that doubleTake doesn't map something in the config.  Something Frigate does correctly, but I can't get it to work with doubleTake.

**Comment by jakowenko** [comment]
> There should be an ingress path, but it appears to me that doubleTake doesn't map something in the config. Something Frigate does correctly, but I can't get it to work with doubleTake.

The [addon does support ingress](https://github.com/jakowenko/double-take-hassio-addons/blob/master/stable/config.json#L11) and mine works through the HA port of 8123. If there's something that needs to change can you let me know.

**Comment by DevTodd** [comment]
Or you can do what I do ... Don't use the API and just use HA to take a snapshot of the camera image when the event is detected, save it locally and push it to mobile.

Here's an example:

```yaml
alias: Gate Person Detection (CATT - MQTT - Frigate - DoubleTake)
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.double_take_gate_camera
    attribute: id
condition: []
action:
  - service: mqtt.publish
    data:
      topic: node-red/gate-camera-catt
      payload: triggered
      qos: "2"
  - service: notify.alexa_media
    data:
      message: Someone has been detected at the gate!
      target:
        - media_player.ecobee_smart_thermostat_premium
      data:
        type: tts
  - service: camera.snapshot
    data:
      filename: /config/media/object-detection/person-gate.jpg
    target:
      device_id: blahblahblah
  - service: notify.mobile_app_pixel_7_pro
    data:
      data:
        image: /media/local/object-detection/person-gate.jpg
        clickAction: app://com.axis.acs
        notification_icon: mdi:face-recognition
        color: red
      message: >-
        {% if state_attr('sensor.double_take_gate_camera', 'personCount') | int
        == 0 %} 
          Someone was detected at the gate.
        {% else -%}
          {% for name in
            state_attr('sensor.double_take_gate_camera', 'matches')
          -%}
            {% if name.match == true %}{{ name.name | title}}{% if not loop.last %}, {% endif -%}
            {% else %}
              An UNKNOWN face
            {% endif %}
          {%- endfor %} {% if
            state_attr('sensor.double_take_gate_camera', 'personCount') | int > 1 %}were detected at the gate.
            {% else -%}was detected at the gate.
          {% endif %}
        {% endif -%}
      title: Person at Gate
mode: single
```
