### ISSUE TITLE
Double Take works but crashes after a few seconds [BUG]

### ISSUE THREAD

**Issue by Quotenjunkie** [jakowenko/double-take#240]
**Describe the bug**
I am using double-take on home assistant (2022.9.2) with frigate (3.1) and deepstack (cpu 2021.09.1) on an intel nuc i3-8109U and everything is configured and after the start-up all the checklights are green and I can train/recognize images directly from frigate. But after a couple of seconds the addon stops and also the watchdog doesn't restart it. Furthermore, there are no errors in the logs

**Version of Double Take**
`1.12.1

**Hardware**
Intel nuc i3-8109U

**Comment by dgriswo** [comment]
I have similar behavior of starting then almost immediately crashing without watchdog restarting.   A lack of logs makes it hard to determine if it is the same issue.

Hardware:
Raspberry Pi 4B 4GB - Homeassistant (2022.9.6) + Double-Take (1.12.1)
Raspberry Pi 4B 8GB - Frigate (0.10.1-83481af + Coral) + Deepstack (2022.01.01 cpu)
Neither Pi uses an SD card.

```
info: Double Take v1.12.1-35874f3
verbose: {
  telemetry: true,
  auth: false,
  detect: {
    match: {
      save: true,
      base64: false,
      confidence: 60,
      purge: 720,
      min_area: 10000
    },
    unknown: {
      save: true,
      base64: false,
      confidence: 40,
      purge: 720,
      min_area: 0
    }
  },
  time: { timezone: 'UTC' },
  frigate: {
    attempts: { latest: 10, snapshot: 10, mqtt: true, delay: 0 },
    image: { height: 500 },
    labels: [ 'person' ],
    update_sub_labels: false,
    stop_on_match: true,
    url: 'https://frigate.nvr.<redacted>.com'
  },
  mqtt: {
    topics: {
      frigate: 'frigate/events',
      matches: 'double-take/matches',
      cameras: 'double-take/cameras',
      homeassistant: 'homeassistant'
    },
    host: 'homeassistant.<redacted>.com',
    username: 'doubletake',
    password: '********'
  },
  logs: { level: 'debug' },
  ui: {
    path: '',
    theme: 'luna-blue',
    editor: { theme: 'nord_dark' },
    logs: { lines: 500 },
    pagination: { limit: 50 },
    thumbnails: { quality: 95, width: 500 }
  },
  detectors: {
    deepstack: {
      timeout: 120,
      opencv_face_required: false,
      url: 'https://deepstack.nvr.<redacted>.com',
      key: '********'
    }
  },
  server: { port: 3000 },
  storage: {
    path: '/config/double-take',
    config: { path: '/config/double-take' },
    secrets: { path: '/config', extension: 'yaml' },
    media: { path: '/media/double-take' },
    tmp: { path: '/dev/shm/double-take' }
  },
  version: '1.12.1-35874f3'
}
verbose: api listening on :3000
info: MQTT: connected
info: MQTT: subscribed to frigate/events, frigate/+/person/snapshot
verbose: 1664932409.789611-s7c4ho - car label not in (person)
```

HA Config:
```
STORAGE_PATH: /config/double-take
CONFIG_PATH: /config/double-take
SECRETS_PATH: /config
MEDIA_PATH: /media/double-take
```

config.yml:
```
mqtt:
  host: !secret mqtt_hostname
  username: !secret doubletake_mqtt_username
  password: !secret doubletake_mqtt_password
  
frigate:
  url: !secret frigate_url
  
detectors:
  deepstack:
    url: !secret deepstack_url
    key: !secret deepstack_api_key
    timeout: 120
    
detect:
  match:
    save: true
    # hours to keep match images until they are deleted
    purge: 720
    # minimum area in pixels to consider a result a match
    min_area: 10000

  unknown:
    # hours to keep unknown images until they are deleted
    purge: 720
    # minimum area in pixels to keep an unknown result
    min_area: 0

logs:
  level: debug
```
