### ISSUE TITLE
Only one dectors works for all cameras[BUG]

### ISSUE THREAD

**Issue by Kouwe-sudo** [jakowenko/double-take#246]
**Describe the bug**
In my configuration I have both Deepstack and Copreface and I want them both to detect persons for a cameras. But where Deepstack works for all cameras Compreface seems to work for only one. The first. Is this a bug or a known feature. I would like them to both recognize a person for  all cameras  so I have less false positives.

**Version of Double Take**
V 1.12.1-35874F3

**Expected behavior**
detection by all detectors.

**Screenshots**

**Hardware**
 - OS: Debian 11
 - Browser (if applicable) [e.g. Chrome, Safari]

**Additional context**
This is the part of the config that is needed:
```
`detectors:
  deepstack:
    url: http://192.xxx.xxx.xxx:5000
    key:
    cameras:
      - frontdorr
      - garage
      - livingroom
      - backyard
      
  compreface:
    url: http://192.xxx.xxx.xxx:8000
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    timeout: 15
    det_prob_threshold: 0.75
    cameras:
      - frontdorr
      - garage
      - livingroom
      - backyard
```
