### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by atv2016** [jakowenko/double-take#258]
Hi @jakowenko 

Few questions if you would:

**1. I don't see the update_sub_labels take effect in frigate. I have set it to false and to true, but no change.**
Is there anything else i need to set ?

Do i need to set object labels for it to start?

In your example code below

frigate settings (default: shown below)

  if double take should send matches back to frigate as a sub label
  NOTE: requires frigate 0.11.0+
  update_sub_labels: false

**2. Is this the total value of the box 20x20 ?3. How do i calculate min_area ?**

  ignore detected areas so small that face recognition would be difficult
 quadrupling the min_area of the detector is a good start
  does not apply to MQTT events
  min_area: 0

**3. Do i need below for sub labels to show ?**
  object labels that are allowed for facial recognition
  labels:
    - person

**4. I'm not sure what is the difference between a latest.jpg, a snapshot.jpg, or what mqtt: true does/means** 
  attempts:
    number of times double take will request a frigate latest.jpg for facial recognition
    latest: 10
    number of times double take will request a frigate snapshot.jpg for facial recognition
    snapshot: 10
    process frigate images from frigate/+/person/snapshot topics
    mqtt: true
    add a delay expressed in seconds between each detection loop
    delay: 0

**5. Do i need to pass the height of my frigate cameras here ? I have a mix of sub streams and 1080P, so what do i enter here?**
  image:
    height of frigate image passed for facial recognition
    height: 500

I'm using DeepStack btw, as i can't use compreface on my celeron. And although its great the add ons are in homeassistant, i feel running either really drags down my HA installation. Now that i'm running DeepStack on a separate server next to frigate, it works much better.

Many thanks,

**Comment by NickM-27** [comment]
1. Set `update_sub_labels` to true and that is all it takes for frigate to set the names once a face is matched as a positive match.
2. Yes, it is in pixels. Doubletake shows the dimensions of the face in the detections page.
3. No, leave it blank as `person` is the default value anyway
4. latest is the full res, full view image from frigate. snapshot is the cropped image of just the object from frigate. mqtt: true tells doubletake to also run face recognition on the mqtt snapshots (similar to other snapshots).
5. yes, you should pass the height so doubletake does not resize the image. You should use the `events` part to set the height per camera

```yaml
frigate:

  url: ...
  update_sub_labels: true
  
  events:
  
    backyard_cam:
      image:
        height: 960
        
    front_doorbell_cam:
      image:
        height: 960
        
    garage_cam:
      image:
        height: 1080
        
    office_cam:
      image:
        height: 1080
```
