### ISSUE TITLE
[FEAT] min_area per camera which is responsible for ignoring detected areas due to its small size

### ISSUE THREAD

**Issue by nordeep** [jakowenko/double-take#269]
**Is your feature request related to a problem? Please describe.**
It would be great to have the possibility to specify `min_area:` per camera as in main `frigate:` section. For now we have `min_area:` per camera for `detect:` but it's not the same. `min_area:` per camera for `detect:` is check to consider to `match:` or `unknown:`.

**Describe the solution you'd like**
For now I have few cameras with high `min_area:` because those cameras are in front and at the level of face I don't want to overload detector with small area. But some wide cameras don't reach `min_area:` 

```
cameras:
  front-door:
    min_area: 10000
```

**Comment by NickM-27** [comment]
You can already do this:

```yaml
cameras:

  backyard_cam:
    detect:
      match:
        save: true
        confidence: 85
        min_area: 3000
      unknown:
        min_area: 2000
        confidence: 75
        
  front_doorbell_cam:
    detect:
      match:
        save: true
        confidence: 90
        min_area: 6500
      unknown:
        min_area: 4000
        confidence: 75
        purge: 48
```
