### ISSUE TITLE
Multiple HA Notifications for the same event

### ISSUE THREAD

**Issue by clowncracker** [jakowenko/double-take#287]
**Describe the bug**
How I stop getting multiple HA notifications for the same event?  I'll get bombarded with notifications in the same event if someone is unrecognized.

**Version of Double Take**
1.13.1

**Expected behavior**
I want one notification for one event.  If someone is unrecognized, I don't want to receive the same notification multiple times while it is trying to recognize someone.

**Screenshots**
Automation YAML:

```
alias: Front Door Automation
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.double_take_unknown
    id: unknown face
  - platform: state
    entity_id:
      - sensor.double_take_jeff
    id: jeff face
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: unknown face
        sequence:
          - service: notify.mobile_app_jeff_s_phone
            data:
              message: Unknown Visitor
              data:
                image: /media/local/double-take/latest/unknown.jpg
                entity_id: camera.front_door
                actions:
                  - action: URI
                    title: Open Camera
                    uri: /lovelace-mushroom/camera
      - conditions:
          - condition: trigger
            id: jeff face
        sequence:
          - service: notify.mobile_app_jeff_s_phone
            data:
              message: You are at the front door!
              data:
                image: /media/local/double-take/latest/unknown.jpg
                entity_id: camera.front_door
                actions:
                  - action: URI
                    title: Open Camera
                    uri: /lovelace-mushroom/camera
mode: single
```

Double Take YAML:

```
mqtt:
  host: xxxx
  username: xxxx
  password: xxxx
  
frigate:
  url: xxxx
  stop_on_match: true #I thought this might help
  attempts:
    latest: 10 #I thought this might help
    snapshot: 10 #I thought this might help
    mqtt: false #I thought this might help
  zones:
    - camera: front_door
      zone: entryway
      
detectors:
  deepstack:
    url: xxxx
    key: 
```

**Hardware**
Deepstack: Unraid Docker
HA: Unraid VM
Frigate: Unraid Docker
Double Take: HA Add-on
