### ISSUE TITLE
[BUG] Matched People Sensors Not Showing Up in HA

### ISSUE THREAD

**Issue by kksligh** [jakowenko/double-take#314]
**Describe the bug**

Everything is working as designed. MQTT, Deepstack and frigate are all connected and working... that said, for some reason, the People I have matched in the model are not showing up as sensors in HA. I see double_take_unknown and I see 3 double take camera sensors, but none of the 4 people I have matched show up. I'm assuming I'm not doing something write or there's a bug of some kind.

**Version of Double Take**
`v1.13.1-8e2728d`

**Expected behavior**
I expect a person sensor to show up in HA so I can use for triggers in automations 

**Screenshots**

**Hardware**
 - OS: Home Assistant 2023.5.3
 - Browser (if applicable) [e.g. Chrome, Safari]

**Additional context**

**Comment by townsmcp** [comment]
@kksligh have you created a sensor yourself in yaml? I found creating my own one, using the names of people I have defined in DT got round this issue:
```

mqtt:  
  sensor:  
    - name: Cheryl    
      icon: mdi:account    
      state_topic: 'double-take/matches/cheryl' 
      json_attributes_topic: 'double-take/matches/cheryl'
      value_template: '{{ value_json.camera }}' 
      availability_topic: 'double-take/available'

```
