### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by CurtisBlumer** [jakowenko/double-take#319]
**Describe the bug**
After installing Double Take in a Docker Container or in Home Assistant, an error is persistently shows and disappears in the bottom left corner stating `Cannot read properties of undefined (reading 'id')`

**Version of Double Take**
`v1.13.1-8e2728d`

**Expected behavior**
I expected no error messages

**Screenshots**
![Screenshot of bug](https://i.imgur.com/mUwoZUJ.png)

**Hardware**
 - OS: Ubuntu 22.04 in LXC/Docker
 - Browser (if applicable) Chrome and Brave

**Additional context**
Fresh install, this happens bother before and after successful configuration

**Comment by Bug23451** [comment]
Same issue here.

Happens when using both Deepstack and compreface either one at a time or simultaneously.

Both detectors are still able to process images.

**Comment by rgriffogoes** [comment]
Looks same as this https://github.com/jakowenko/double-take/issues/313#issuecomment-1560064936

Issue on version check requests failing as latest release workflow logs got displaced by CodeQL runs.

Also same as #317

**Comment by Majestic7979** [comment]
I also have this issue.

**Comment by Knaackee** [comment]
I have the same issue. The Status of Double Take, Frigate and Deepstack is green though.

```yaml
mqtt:
  host: 192.168.188.86
  username: ****
  password: ****
  
frigate:
  url: http://192.168.188.86:5000
  
detectors:
  deepstack:
    url: http://192.168.188.86:5050
```
