### ISSUE TITLE
[BUG] Unknown inidividuals aren't being marked as unknown

### ISSUE THREAD

**Issue by clowncracker** [jakowenko/double-take#322]
**Describe the bug**
Unknown individuals are being marked as matches with low confidence instead of unknown.  Example:

Random person walks to the camera, it's identified as casey with a 7.48% certainty.  This should be identified as unknown.

**Version of Double Take**
1.13.1 in Home Assistant

**Expected behavior**
I expect anyone not matched to be considered unknown.

**Screenshots**
[Screenshot of issue](https://imgur.com/a/A4CtGsE)

**Hardware**
 - OS: Home Assistant Core 2023.6.2

**Additional context**

**Comment by townsmcp** [comment]
@clowncracker please add your full DT configuration. Without it no one can help you

**Comment by tyanai** [comment]
I also having the same exact problem.

Whenever the image is unknown, I'm seeing this in the doubletake log:

23-06-25 16:10:08 info: done processing reolink_cam: 1687709372.470719-uovc1f in 35.49 sec
23-06-25 16:10:08 info: {
  id: '1687709372.470719-uovc1f',
  duration: 35.49,
  timestamp: '2023-06-25T16:10:08.472Z',
  attempts: 22,
  camera: 'reolink_cam',
  zones: [ 'Entrance_porch' ],
  counts: { person: 0, match: 0, miss: 0, unknown: 0 },
  matches: [],
  misses: [],
  unknowns: []
}

**Frigate Config:**

mqtt:
  host: 192.168.1.200
  user: admin
  password: XXXX
go2rtc:
  streams:
    reolink_entrance: 
      - http://192.168.1.231/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=XXXX
      - "ffmpeg:reolink#audio=opus"
    reolink_entrance_sub: 
      - http://192.168.1.231/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=XXXX

cameras:
  reolink_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_entrance?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_entrance?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 1280,0,1280,720,699,720,569,398,744,82,620,0,258,108,0,583,0,0
    zones:
      Entrance_porch:
        coordinates: 601,496,692,720,30,720,249,258,339,512
        objects:
          - person
      Entrance_pathway:
        coordinates: 483,124,648,483,333,495,228,142
        objects:
          - person
      Entrance_before_gate:
        coordinates: 266,146,789,172,642,44,380,69
        objects:
          - person
    objects:
      track:
        - person
      mask:
        - 1280,0,1280,720,699,720,569,398,744,82,620,0,258,108,0,583,0,0
    snapshots:
      enabled: true
      bounding_box: true
      retain: 
        default: 2
      required_zones:
        - Entrance_porch
        - Entrance_pathway
        - Entrance_before_gate
    mqtt:
      timestamp: true
      bounding_box: true
      crop: true
      quality: 100
      height: 1500
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        dog: 2
        car: 7

live:
  stream_name: reolink_entrance
  height: 1920
  quality: 8
birdseye:
  enabled: True
  mode: continuous
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

**DoubleTake Config:**

frigate:
  url: http://192.168.1.200:5000
  update_sub_labels: true
  
  min_area: 0

  labels:
    - person
    
  attempts:
    latest: 22
    snapshot: 0
    mqtt: false
    delay: 1.25
  
  image:
    height: 1500

mqtt:
  host: 192.168.1.200
  username: admin
  password: Gazoz010
  topics:
    frigate: frigate/events
    homeassistant: homeassistant
    matches: double-take/matches
    cameras: double-take/cameras



detectors:
  compreface:
    url: http://192.168.1.200:8000/
    key: XXXX
    det_prob_threshold: 0.7
  
telemetry: false


  
detect:
  match:
    save: true
    base64: false
    confidence: 80
    purge: 168
    min_area: 2000

  unknown:
    save: true
    base64: false
    confidence: 40
    purge: 168
    min_area: 0

**Comment by townsmcp** [comment]
@tyanai change your ‘unknown’ ‘confidence’ from 40 to 80. The issue is there is a gap between known (at 80%) and unknown at 40%. You need unknown to cross to known with no gap. For reference my DT config is the following (I use 85% confidence) and all unknowns are being marked as unknown:
```

# Double Take
# Learn more at https://github.com/jakowenko/double-take/#configuration



# "Snapshot" -- frame from frigate, saved then frigate detect an event (motion, for example)
# "Latest" -- frame from camera, on the moment then double-take trying to make an recognition (Usually, the difference between them is 1-2 seconds)
# "MQTT" -- The frame that the frigate transmitted with the event by MQTT protocol. It's usually equivalent to "snapshot", but depends on frigate settings

# If u use double-take in conjunction with frigate, the "snapshot" method will be enough

# Want either MQTT or Snapshot. MQTT does not include zone

home_assistant:
  url: http://192.168.1.198:8123
  token: %TOKEN_VALUE%

frigate:
  url: http://192.168.1.158:5000
  update_sub_labels: True
  # stop the processing loop if a match is found
  # if set to false all image attempts will be processed before determining the best match
  stop_on_match: True
  # ignore detected areas so small that face recognition would be difficult
  # quadrupling the min_area of the detector is a good start
  # does not apply to MQTT events
  #min_area: 1600

  # object labels that are allowed for facial recognition
  labels:
    - person
    
  attempts:
    # number of times double take will request a frigate latest.jpg for facial recognition
    latest: 0
    # number of times double take will request a frigate snapshot.jpg for facial recognition
    snapshot: 10
    # process frigate images from frigate/+/person/snapshot topics
    mqtt: false
    # add a delay expressed in seconds between each detection loop
 #   delay: 0
 
  # only process images from specific zones
  zones:
    - camera: doorbell
      zone: garden_doorbell
    - camera: car-port
      zone: driveway_carport
  
mqtt:
  host: 192.168.1.198
  username: %MQTT_USERNAME_VALUE%
  password: %MQTT_PASSWORD_VALUE%
  
detectors:

#If you want no match then increase det_prob_threshold: 80 a little at a time and re-test your matches… it will return nothing if it fails this test. I have been creeping this value up and it has really reduced the number of images accepted and false positives from blurry movement shots etc.

#detectors:
  #compreface:
    # minimum required confidence that a recognized face is actually a face
   # det_prob_threshold: 0.98
  compreface:
    url: http://192.168.1.158:8000
    # recognition api key
    key: %KEY_VALUE%
    # number of seconds before the request times out and is aborted
    timeout: 15
    # minimum required confidence that a recognized face is actually a face
    # value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # require opencv to find a face before processing with detector
    opencv_face_required: false
    # comma-separated slugs of face plugins
    # https://github.com/exadel-inc/CompreFace/blob/e1ee791cac6cd9b1d3a9ea2cb129c78cb00a9083/docs/Face-services-and-plugins.md)
    # face_plugins: mask,gender,age
    # only process images from specific cameras, if omitted then all cameras will be processed
    # cameras:
    #   - front-door
    #   - garage
#  aiserver:
#    url: http://192.168.1.158:32168
    # number of seconds before the request times out and is aborted
 #   timeout: 15
    # require opencv to find a face before processing with detector
#    opencv_face_required: false
telemetry: false


    
      
detect:
  match:
    # save match images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed to consider a result a match
    confidence: 85
    # hours to keep match images until they are deleted
    purge: 24
    # minimum area in pixels to consider a result a match
    min_area: 2500
    #when using substream image, 3600

  unknown:
    # save unknown images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed before classifying a name as unknown
    confidence: 85
    # hours to keep unknown images until they are deleted
    purge: 8
    # minimum area in pixels to keep an unknown result
    min_area: 64

```

Also, according to the log it is taking a very long time to reach a decision. The ‘attempts’ should be able to be reduced significantly. Might also pay to add the ‘stop_on_match’ to true?
Throwing a Google Coral into the mix would help Frigate out significantly, and hardware acceleration too. I am using a PCIe rather than USB Coral and inference went down from 200 to 7
