### ISSUE TITLE
[BUG] most faces are not matching because under 100x100

### ISSUE THREAD

**Issue by timknowlden** [jakowenko/double-take#329]
**Describe the bug**
Detector showing red for match because most box sizes are below 100x100

**Hardware**
 Unraid OS

**Additional context**
Frigate, doubletake and deepstack

Is this a frigate or doubletake config issue, how can I increase the image size and box?
![1000021953](https://github.com/jakowenko/double-take/assets/73787006/7fef2367-1982-4814-a988-b30109e47b82)

**Comment by DieMetRik** [comment]
I have the same issue with deepstack detector.
I switched to Compreface it solve issue with low % of face recognition

If you want to increase resolution of box -> increase resolution in camera settings and in Frigate detect section
frigate config file:
``````
    detect:
      width: 1920
      height: 1080
      fps: 5
``````

You also can decrease value in double-take config
``````
detect:
  match:
    # minimum area in pixels to consider a result a match
    min_area: 10000 
``````
min_area it's size of orange box in pixel: 100 * 100 = 10000
if you need 80 * 80 = 6400
