### ISSUE TITLE
[BUG] Amazon Rekognition Training not successful (error 500 / 502)

### ISSUE THREAD

**Issue by vdiogo** [jakowenko/double-take#353]
**Describe the bug**
I have recently started using Amazon Rekoginition in paralel with Compreface, and haven't been able to train the model when Double-Take returns unknown face recognition.

As an example, when I select an image an apply a label, I jump to the Train tab of Double-Take, and wait until the page loads (while training is in process) and get an error message saying Error 500. Slightly after that (couple of minutes) I get multiple Error 502 messages.

This is my Double-Take configuration for Rekognition:
```
  rekognition:
    aws_access_key_id: !secret aws_access_key
    aws_secret_access_key: !secret aws_secret_access_key
    aws_region: eu-west-1 #this is in Ireland, default is us-east-1
    collection_id: double-take
    opencv_face_required: true

```

**Version of Double Take**
`v1.13.11.8`

**Expected behavior**
Would expect that by applying the label to an image, that the model would be trained and would start getting subsequent images recognized by the model

**Screenshots**
1. Select image and apply label
<img width="326" alt="image" src="https://github.com/user-attachments/assets/dc78a1f1-673b-438d-b306-71b9c33dbeb0">

2. Check training status
<img width="991" alt="image" src="https://github.com/user-attachments/assets/76f715d2-3cd7-41c9-b14e-240d792e0c7c">

3. Request fails
<img width="1343" alt="image" src="https://github.com/user-attachments/assets/69a54cf4-3bbb-471e-b492-66baa1534f51">

4. Images appear as trained, but new (or tarined) images don't show the label applied

<img width="1343" alt="image" src="https://github.com/user-attachments/assets/8acd6f15-9e52-4e6e-b40d-f69c64869521">

**Hardware**
 - OS: running double-take in Home Assistant (HACS)
 - Browser: Chrome

**Additional context**
Cannot find any useful info in the logs (including a reference to those error messages)
