### ISSUE TITLE
Ability to define minimum box size 

### ISSUE THREAD

**Issue by MrNorm** [jakowenko/double-take#42]
Fantastic project, which slotted perfectly into my Frigate + HA setup. Thank you.

I'm using DeepStack for the facial recognition here. I noticed that sometimes Frigate picks up a person quite far away and sends that image over to double take, even after playing with the min/max area filters.

Because of this, the face box for facial recognition is very small and for me, produces results with false high confidence matches despite not much face being present. Examples below:

![image](https://user-images.githubusercontent.com/64325/118176327-2e659480-b429-11eb-86df-2eb046e32699.png)
![image](https://user-images.githubusercontent.com/64325/118176436-5228da80-b429-11eb-89c0-75e7dc745584.png)

Can I set the minimum face 'box size' or set anything else to help results?

Thanks!

**Comment by jakowenko** [comment]
Thanks for the kind words @MrNorm. If you're running the beta build, I just pushed an update to support this.

I've updated the [README](https://github.com/jakowenko/double-take/tree/beta#configuration) to show how to configure it. By default it's set to 10,000 pixels. So any results that are smaller than 100x100 won't be counted as a match. Let me know if this solves the problem you had.

```yaml
objects:
  face:
    min_area_match: 10000
```

**Comment by MrNorm** [comment]
Thanks for taking a look so quickly!

I switched to the `beta` tag and have created a `config.yml` which seems to be picking up OK, as MQTT and DeepStack are connected.. but I'm afraid the face boxes are still under the threshhold.

I may be doing something wrong here. Are my settings correct?

```
server:
  port: 3000

objects:
  face:
    min_area_match: 10000

mqtt:
  host: 192.168.0.8
  username: <redacted>
  password: <redacted>

frigate:
  url: http://192.168.0.9:5000

detectors:
  deepstack:
    url: http://192.168.0.2:5000

time:
  format: F
  timezone: Europe/London
```

Latest sample with box size of 2418 pixels

![image](https://user-images.githubusercontent.com/64325/118245610-f1d18180-b498-11eb-8dac-b070f618dddd.png)
