### ISSUE TITLE
Usage of Age / Gender etc. from Compreface

### ISSUE THREAD

**Issue by Chreece** [jakowenko/double-take#47]
Hello David,
Thank you very much for sharing your great project!
I think it is a must have for the Smart Home enthusiasts...

What do you think about adding support for the new plugins from Compreface like Age and Gender recognition?

I would like to read your thoughts...

Keep up helping the community :D

**Comment by jakowenko** [comment]
I'm glad you are finding the project useful and thank you for the suggestion!

I'd definitely love to support this feature. I was looking a little closer at it last night. Do you see this running at the same time recognition happens? Maybe showing all the age / gender info on that UI card element for each picture?

**Comment by jakowenko** [comment]
Hey @Chreece, I added support for this feature to the beta build if you want to test it out.

You'll just need to update the `config.yml` to pass in the `face_plugins` like so:

```yaml
detectors:
  compreface:
    url: http://192.168.1.217:8000
    key: xxx-xxx-xxx-xxx
    face_plugins: age,gender
```

I've added two new badges to the UI if the values are present. I'm currently only accounting for the age and gender plugins.

<img width="495" alt="Screen Shot 2021-05-24 at 10 00 56 PM" src="https://user-images.githubusercontent.com/1081811/119428908-c4c47080-bcdb-11eb-939f-36495d43dff0.png">

**Comment by jakowenko** [comment]
Hey @Chreece, I added support for this feature to the beta build if you want to test it out.

You'll just need to update the `config.yml` to pass in the `face_plugins` like so:

```yaml
detectors:
  compreface:
    url: http://localhost:8000
    key: xxx-xxx-xxx-xxx
    face_plugins: age,gender
```

I've added two new badges to the UI if the values are present. I'm currently only accounting for the age and gender plugins.

<img width="495" alt="Screen Shot 2021-05-24 at 10 00 56 PM" src="https://user-images.githubusercontent.com/1081811/119428908-c4c47080-bcdb-11eb-939f-36495d43dff0.png">
