### ISSUE TITLE
Everything seems to work but Double Take did not catch snapshot

### ISSUE THREAD

**Issue by dimitribellini** [jakowenko/double-take#68]
Hi,
Thanks for your great project! 
I have configure on my HomeAssistantOS (v2021.7.4) the Frigate Software (v.1.13-0.8.4 - Coral TPU) and a Vm with DoubleTake (v.0.9.1) and CompreFace (v.0.5.1). 
The training part of Double Take is working great and also for some days the integration with Frigate MQTT Snapshot but from some days the Frigate part is not working anymore...
I have tested all the possible permutation :-) 
- Fresh new installation of Home Assistant -> Nothing
- Changing all the parameters of DoubleTake config -> Nothing
- Changing all the parameters of Frigate config -> Nothing
- Clean install of MQTT Mosquito on HomeAssistant -> Nothing

I know is not easy to understand why this happen only to me.. but there is a way to debug what happen from Frigate to DoubleTake side?

I will attache my Frigate and DoubleTake config.
Thanks so mach for all possible help
------------------
**file: frigate.yml**
```
mqtt:
  host: 192.168.0.40
  user: *****
  password: *****

logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: debug

cameras:
  bunny:
    ffmpeg:
      inputs:
        - path: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
          roles:
            - detect
            - clips
    width: 240
    height: 160
    fps: 5
    objects:
      track:
       - person
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 2
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 500
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False
detectors:
  coral:
    type: edgetpu

```
---
file: doubletake config
```
# Double Take
server:
  port: 3000

mqtt:
  host: 192.168.0.40
  mqtt.username: *****
  mqtt.password: *****
  topics:
    frigate: frigate/events
    matches: double-take/matches
    cameras: double-take/cameras

confidence:
  match: 60
  unknown: 10

objects:
  face:
    min_area_match: 10000

save:
  matches: true
  unknown: true

purge:
  matches: 168
  unknown: 8

frigate:
  url: http://192.168.0.40:5000
  image:
    height: 500
  attempts:
    latest: 10
    snapshot: 0
  cameras:
    #- ufficio
    - sala
    - bunny
    
detectors:
  compreface:
    url: http://192.168.0.96:8000
    key:  # key from recognition service in created app

time:
  format: F
  timezone: Europe/Rome
```

**Comment by dimitribellini** [comment]
Was my fault! as suggested by Jako on discord...
I made a wrong configuration for MQTT in Double Take config.
The right one is : 
```
mqtt:
  host: 192.168.0.40
  username: *****
  password: *****
```
Without **"mqtt."**

Thanks so much for the help!
