### ISSUE TITLE
Question: Does mobile train work with iphone (take photo or upload from library)?

### ISSUE THREAD

**Issue by ragenhe** [jakowenko/double-take#81]
It doesn't matter how I ingest the photo to train with, deepstack confirms success and Facebox says no face detected.

What am I missing?

No errors in the facebox container.  It just won't detect/train.

I am starting it within docker-compose.

```
facebox:
    image: machinebox/facebox
    container_name: facebox
    restart: always
    ports:
      - 8000:8080
    environment:
      - "MB_KEY=<redacted>"
    networks:
      - intproxy
```
