### ISSUE TITLE
Feature Request: Compreface Mask (Covid19) recognition.

### ISSUE THREAD

**Issue by Chreece** [jakowenko/double-take#85]
Hello there!

I just read in the new features from Compreface 0.6.0:

`Mask recognition plugin. We added a new plugin that returns if the person wears a mask and if yes - if it's worn correctly`

I know that 99% don't need this feature, but if we have this info available, why not have double-take read it?

Have fun!

**Comment by jakowenko** [comment]
Hey, I just pushed a new beta build to include support for this. Below is an example of how it's displayed in the UI. I used the test image CompreFace had in their docs.

Plugins can be passed in the config this like.

```yaml
detectors:
  compreface:
    url: http://192.168.1.217:8000
    key: 10296f1e-247a-4c00-be88-8ccb70deab64
    face_plugins: mask,gender,age
```

![Screen Shot 2021-09-03 at 3 51 02 PM](https://user-images.githubusercontent.com/1081811/132059405-54e04516-0dd6-43b5-8ca6-a80f59ce4ca9.png)
