### ISSUE TITLE
Question: Compreface RED vs GREEN?

### ISSUE THREAD

**Issue by ozett** [jakowenko/double-take#90]
i had a match, and compreface-button is green,
i had somehow another match, re-recognized, and compreface state correct person, but is in RED.
why is this?

![image](https://user-images.githubusercontent.com/5937811/132125190-5abcb4e7-4c10-4b2d-8511-bee681bc3958.png)

**Comment by jakowenko** [comment]
This is likely due to the `min_area_match` value being too low in the image in the right. To be considered a match the percentage and area of the bounding box both need to match the defined values.

The default value is `10000`, which means any image below 100x100 won't be counted as a match. I have a lower value set on my personal setup. This is how you can override the default.

```yaml
objects:
  face:
    min_area_match: 2500
```

**Comment by ozett** [comment]
i will give this a try.

maybe helpful to anchor the Readme.md section with this options, to link to in such issues?

another one: could be FR to have such settings per camera?
because some cams shoot a face from far distance, other from near, so the value could be camera-specific different?

**Comment by jakowenko** [comment]
What do you think of this update on the matches page? Anytime a result is considered a "miss" then the output of why it was a miss will be below the row. You can also now hover over the green/red label to show what it means.

![Screen Shot 2021-09-07 at 2 30 27 AM](https://user-images.githubusercontent.com/1081811/132295414-eb74585a-45ca-4abf-a3d6-f6b49220425d.png)

**Comment by ozett** [comment]
detail information below the red/green matches button is great!

i think the hover dont help. because red is obviously a miss.
the hover would only help, if it gives precise information about the cause for the miss.
like ``` miss of low confidence ```  or ``` miss of low box & low conf``` , but is already stated below.

maybe this details should be also written in red color?
or the box information or the confidence information should be written in red? if thats the cause for misses?

**Comment by jakowenko** [comment]
I slightly changed the UI and decided to put the messages in a tooltip to reduce the height of those cards. I like the idea of using red to indicate what was missed, what do you think of this?

![Screen Shot 2021-09-09 at 1 05 35 AM](https://user-images.githubusercontent.com/1081811/132626070-c7663b22-ac36-48ee-a9a8-64c555e5b036.png)

**Comment by ozett** [comment]
looks good. i will try how this feels in my checking daily routine
can i pull a new beta?

**Comment by jakowenko** [comment]
> looks good. i will try how this feels in my checking daily routine
> can i pull a new beta?

Yes, the new beta should have it.

**Comment by ozett** [comment]
lots of small-area detection are matches. 
i know the category-detection is correct
.. what to do about this?

![image](https://user-images.githubusercontent.com/5937811/132640294-8a44ba3a-9e96-4437-ad94-4d2097956823.png)

**Comment by jakowenko** [comment]
How are you hoping to treat that image? Because you have the `min_area_match` set to `2500` it won't ever consider a result a match if the area is smaller than that.

**Comment by ozett** [comment]
i can test to set min-area that low <600 to get all small faces.
will see if that causes more false-positives... thx, it try and i will report back, until than on hold...

**Comment by ozett** [comment]
i can zone-out same areas, but to prevent from false-positives i need a ```min_area_match``` per camera.
the general value hits all cams, but others cams a fine with that value.

make a FR: ```min_area_match``` per camera.
![image](https://user-images.githubusercontent.com/5937811/132817242-92ea7fcd-2627-40d2-9eeb-8c59da40b21c.png)

**Comment by jakowenko** [comment]
> i can zone-out some areas on that specific cam, but to prevent from false-positives i need a `min_area_match` per camera.
> the general value hits all cams, but others cams a fine with that value.
> 
> make a FR: `min_area_match` per camera.
> ![image](https://user-images.githubusercontent.com/5937811/132817242-92ea7fcd-2627-40d2-9eeb-8c59da40b21c.png)

Ah makes sense. I can try to work on making it a setting per camera over the weekend.

**Comment by ozett** [comment]
Great news! thx 🎁  😄

**Comment by ozett** [comment]
maybe you send matches ```& misses``` over MQTT ? separate topic?

i could ignore ```min_area_match``` in a second_step if i get all the log-info over mqtt.
that way i could consider high-configdence a match in a second step myself

discovered the log and found this helpful . would be great to get it over mqtt...

![image](https://user-images.githubusercontent.com/5937811/132889684-cd914741-e4ae-464f-baa9-c1ad406d1959.png)

**Comment by jakowenko** [comment]
I have the per camera setting just about done. Working on updating the README now. I changed a few other things too with how confidence and some settings are defined. You'll be able to do more at a per camera level.

Global settings will look like this.

```yaml
# global detection settings (default: shown below)
detect:
  match:
    # save match images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed to consider a result a match
    confidence: 60
    # hours to keep match images until they are deleted
    purge: 168
    # minimum area in pixels to consider a result a match
    min_area: 10000

  unknown:
    # save unknown images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed before classifying a match name as unknown
    confidence: 40
    # hours to keep unknown images until they are deleted
    purge: 8
    # minimum area in pixels to keep an unknown result
    min_area: 0
```

And then the new per camera settings.

```yaml
cameras:
  front-door:
    snapshot:
      # apply masks before processing image
      masks:
        # list of x,y coordinates to define the polygon of the zone
        coordinates:
          - 1920,0,1920,328,1638,305,1646,0
        # show the mask on the final saved image (helpful for debugging)
        visible: false
        # size of camera stream used in resizing masks
        size: 1920x1080

      # override global detect variables per camera
      detect:
        match:
          # save match images
          save: true
          # include base64 encoded string in api results and mqtt messages
          # options: true, false, box
          base64: false
          # minimum confidence needed to consider a result a match
          confidence: 60
          # minimum area in pixels to consider a result a match
          min_area: 10000

        unknown:
          # save unknown images
          save: true
          # include base64 encoded string in api results and mqtt messages
          # options: true, false, box
          base64: false
          # minimum confidence needed before classifying a match name as unknown
          confidence: 40
          # minimum area in pixels to keep an unknown result
          min_area: 0
```

I also moved the masks stuff here now because it makes more sense to keep it nested with the other camera settings.

I'll tag this issue in the commit when I push it to the beta build.

**Comment by ozett** [comment]
config section for cameras looks like in frigate-config.
keep that similar, thats good!

> I'll tag this issue in the commit when I push it to the beta build.
(do i get notice somwehow about time for pulling the beta? i am not that experienced with commit handling...)

**Comment by jakowenko** [comment]
The [actions](https://github.com/jakowenko/double-take/actions) page on the repo will show you when the build is done. I just did the last little update for the night, so should be good to pull now.

I need to test it more tomorrow, but everything I did tonight was working as intended. If you run into any weird issues let me know.

**Comment by ozett** [comment]
how is the new config-snytax handelt?
do i have to pull the beta, start with the old-config and re-write?
or must the config-change for the new option done beforhand on the file?

**Comment by jakowenko** [comment]
You can leave your old config on there and start running the new build, it'll just use all the defaults. Then just update it from the UI to match the new format.

**Comment by ozett** [comment]
```
masks:
        # list of x,y coordinates to define the polygon of the zone

VALUES SHOULD DIRECTLY GO HERE?

        #- 3599,1896,1229,207,44,201,30,2118
        coordinates:
          #- 1920,0,1920,328,1638,305,1646,0
          - 1403,608,2485,1520,0,1520,664,592
        # show the mask on the final saved image (helpful for debugging)
        visible: true
```

maybe the new sub-section "coordinates" is not like in frigate. and can be ommited?

**Comment by jakowenko** [comment]
coordinates is required in the masks section now. This is what my test one looks like. The coordinate values are copied directly from Frigate.

```yaml
cameras:
  manual:
    masks:
      coordinates:
        - 1920,0,1920,328,1638,305,1646,0
        # - 0,1080,296,1080,322,827,0,835
      visible: true
      size: 1920x1080
```

**Comment by jakowenko** [comment]
Closing since this is now included in the `1.0.0` release.

**Comment by djdubd** [comment]
> 
Sorry if this unnecessarily re-opens this issue. I had a question about the per camera mask camera stream size.

```yaml
cameras:
  front-door:
    snapshot:
      # apply masks before processing image
      masks:
        # list of x,y coordinates to define the polygon of the zone
        coordinates:
          - 1920,0,1920,328,1638,305,1646,0
        # show the mask on the final saved image (helpful for debugging)
        visible: false
        # size of camera stream used in resizing masks
        size: 1920x1080
```
The description in the comment says "size of camera stream used in resizing masks" is this the 'detect' stream or the 'record' stream in frigate? Thanks!
